### ISSUE TITLE
KOPS -- Readiness probe failed: HTTP probe failed with statuscode: 404

### ISSUE THREAD

**Issue by wickstargazer** [zalando/skipper#644]
Hi, 

The skipper is throwing this Readiness probe failed: HTTP probe failed with statuscode: 404
and making the cluster unhealthy.

Please guide me on how to fix this, thank you

**Comment by szuecs** [comment]
How do you start skipper? Flags and setup would be great.

Did you use documentation? If so which?

**Comment by wickstargazer** [comment]
Hi,
I used the documentation. This is in a private VPC. I just used the exact YML that you guys provided us with, not changing anything except its in a private VPC.

Regards

**Comment by HerrmannHinz** [comment]
RBAC error?

**Comment by szuecs** [comment]
Probably this issue was the same as reported at https://github.com/zalando/skipper/issues/647.
This is fixed in release v0.10.7

**Comment by wickstargazer** [comment]
Hi its still happening even after fixing the version. These are the logs, i have been reading extensively and am not sure if its the VPC range that is not covered in the fixed values that is in the code?
What i mean is this

` level=info msg=\"route settings, update, route: kube__healthz: Path(\\\"/kube-system/healthz\\\") \u0026\u0026 Source(\\\"10.0.0.0/8\\\", \\\"192.168.0.0/16\\\", \\\"172.16.0.0/12\\\", \\\"127.0.0.1/8\\\", \\\"fd00::/8\\\", \\\"::1/128\\\") -\u003e status() -\u003e \u003cshunt\u003e\"\n","stream":"stderr","time":"2018-01-03T20:50:56.009538864Z"}`

```
172.32.x.x - - [16/May/2018:09:24:15 +0000] "GET /kube-system/healthz HTTP/1.1" 404 10 "-" "kube-probe/1.8" 0 172.32.x.x:9999 - -
172.32.x.x - - [16/May/2018:09:24:25 +0000] "GET /kube-system/healthz HTTP/1.1" 404 10 "-" "kube-probe/1.8" 0 172.32.x.x:9999 - -
```

**Comment by szuecs** [comment]
@wickstargazer this is health check issue, because we currently only whitelist all "internal" networks from IPv4 rfc as far as I remember. You might need a flag that adds your IP address space to this list.

The list is defined at https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/kube.go#L55
Below you see the Options where we could pass an additional list of CIDR to put into the list on data client creation.
